name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.0.1" # Define the OTP version [required]
          elixir-version: "1.12.1" # Define the elixir version [required]
          experimental-otp: true
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test_with_retry --color
 